### ISSUE TITLE
希望可以有一个24小时制的时间样式

### ISSUE THREAD

**Issue by Azraeltulips** [agiapp/BRPickerView#106]
在设置时间样式为ModeTime时，希望可以有一个24小时制的时间样式，而不是用上午和下午来区分

**Comment by Azraeltulips** [comment]
补充：虽然有BRDatePickerModeHM，但这个样式不能循环滚动，在滚动到23时，需要回头滚动

**Comment by 91renb** [comment]
`BRDatePickerModeCountDownTimer` 和  `BRDatePickerModeHM` 都是24小时制的时间样式

**Comment by 91renb** [comment]
BRDatePickerModeCountDownTimer 支持循环滚动
