### ISSUE TITLE
我想传模型进去

### ISSUE THREAD

**Issue by Sun7400** [agiapp/BRPickerView#113]
[
<img width="962" alt="企业微信截图_5d879f81-2a42-448b-9b8f-8be515394fbd" src="https://user-images.githubusercontent.com/14027528/71616002-00dec900-2bef-11ea-9ecd-c825e0bd728f.png">
](url)

比如这样的数据结构，我显示是value 但是我怎么根据 vlaue找到对应的key呢用这个控件，就是说我选择的怎么和key对应起来，我要拿到对用的key

**Comment by 91renb** [comment]
在 model 里 加一个索引 index 属性，把value数组传进字符串选择器，回调结果有返回index，再根据index找到去模型数组里拿到对应的模型，然后 key、value、remark 都能拿到

**Comment by Sun7400** [comment]
这样有点麻烦了

**Comment by 91renb** [comment]
其实也不麻烦，只是多了一个步骤（遍历模型数组，获取value数组）。
2.5.1版本已优化了这个问题，添加支持数据源直接传模型数组。pod更新一下，使用如下：
```
/// 融资情况
NSArray *infoArr = @[@{@"key": @"1001", @"value": @"无融资", @"remark": @""},
                     @{@"key": @"2001", @"value": @"天使轮", @"remark": @""},
                     @{@"key": @"3001", @"value": @"A轮", @"remark": @""},
                     @{@"key": @"4001", @"value": @"B轮", @"remark": @""},
                     @{@"key": @"5001", @"value": @"C轮以后", @"remark": @""},
                     @{@"key": @"6001", @"value": @"已上市", @"remark": @""}];
NSMutableArray *modelArr = [[NSMutableArray alloc]init];
for (NSDictionary *dic in infoArr) {
    BRResultModel *model = [[BRResultModel alloc]init];
    model.key = dic[@"key"];
    model.value = dic[@"value"];
    model.remark = dic[@"remark"];
    [modelArr addObject:model];
}
[BRStringPickerView showPickerWithTitle:@"融资情况" dataSourceArr:[modelArr copy] selectIndex:1 resultBlock:^(BRResultModel *resultModel) {
    textField.text = resultModel.value;
    NSLog(@"选择的值[%@]：%@", @(resultModel.index), resultModel.value);
}];
```

**Comment by Sun7400** [comment]
好的谢谢，这个库很优秀。能加个微信吗……我的微信m1358836531------------------ 原始邮件 ------------------
发件人: "91renb"<notifications@github.com>
发送时间: 2020年1月6日(星期一) 上午8:46
收件人: "91renb/BRPickerView"<BRPickerView@noreply.github.com>;
抄送: "SunMengK"<1358836531@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [91renb/BRPickerView] 我想传模型进去 (#113)



其实也不麻烦，只是多了一个步骤（遍历模型数组，获取value数组）。
 2.5.1版本已优化了这个问题，添加支持数据源直接传模型数组。pod更新一下，使用如下：
 /// 融资情况 NSArray *infoArr = @[@{@"key": @"1001", @"value": @"无融资", @"remark": @""},                      @{@"key": @"2001", @"value": @"天使轮", @"remark": @""},                      @{@"key": @"3001", @"value": @"A轮", @"remark": @""},                      @{@"key": @"4001", @"value": @"B轮", @"remark": @""},                      @{@"key": @"5001", @"value": @"C轮以后", @"remark": @""},                      @{@"key": @"6001", @"value": @"已上市", @"remark": @""}]; NSMutableArray *modelArr = [[NSMutableArray alloc]init]; for (NSDictionary *dic in infoArr) {     BRResultModel *model = [[BRResultModel alloc]init];     model.key = dic[@"key"];     model.value = dic[@"value"];     model.remark = dic[@"remark"];     [modelArr addObject:model]; } [BRStringPickerView showPickerWithTitle:@"融资情况" dataSourceArr:[modelArr copy] selectIndex:1 resultBlock:^(BRResultModel *resultModel) {     textField.text = resultModel.value;     NSLog(@"选择的值[%@]：%@", @(resultModel.index), resultModel.value); }];  
&mdash;
