### ISSUE TITLE
调用BRStringPickerView类方法崩溃

### ISSUE THREAD

**Issue by zhou1043868875** [agiapp/BRPickerView#115]
[BRStringPickerView showPickerWithTitle:@"标题" dataSourceArr:@[@"男", @"女", @"未知"] selectIndex:1 resultBlock:^(BRResultModel *resultModel) {
        NSLog(@"%@,%@", resultModel.ID,resultModel.name);
    }];崩溃
原因：_isDataSourceValid默认值NO，NSAssert(!strPickerView->_isDataSourceValid, @"数据源不合法！请检查字符串选择器数据源的格式");
解决办法：调用handlerDefaultSelectValue对_isDataSourceValid初始化YES
建议：开发中尽量使用系统默认的NO来作为默认值，避免初始化遗漏出现的问题

**Comment by 91renb** [comment]
多谢建议👍，已更新。并添加了支持数据源直接传模型数组
