### ISSUE TITLE
字符串选择好像不支持联动吧？

### ISSUE THREAD

**Issue by fuyunmanbu** [agiapp/BRPickerView#118]

**Comment by 91renb** [comment]
是的，后续会考虑扩展这一功能

**Comment by fuyunmanbu** [comment]
👌💪



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 91renb <notifications@github.com&gt;
发送时间: 2020年1月9日 12:38
收件人: 91renb/BRPickerView <BRPickerView@noreply.github.com&gt;
抄送: fuyunmanbu <1106859283@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[91renb/BRPickerView] 字符串选择好像不支持联动吧？ (#118)




是的，后续会考虑扩展这一功能

**Comment by Guanzhangpeng** [comment]
关注

**Comment by OmgKevin** [comment]
这个二级数组联动选项功能，期望得到一些帮助，保持关注

**Comment by 91renb** [comment]
该功能已实现，字符串选择器新增支持多级联动选择，请参看Demo进行使用
