### ISSUE TITLE
如何更新数据源

### ISSUE THREAD

**Issue by deepindo** [agiapp/BRPickerView#119]
作者好，

我在使用您的库的时候，展示数据不是不变，是每次弹出都要请求接口获取最新的数据，但是发现我每次点击，请求了接口，也重新给数据赋值了，展示的还是上一次的数据，盼回复，谢谢！

**Comment by 91renb** [comment]
由于库使用的是懒加载方式去初始化各项数据，所以如果要动态更新数据源，需要重新去创建选择器对象。
