### ISSUE TITLE
急求！自定位样式的国际化只支持BRDatePickerModeYM这个吗

### ISSUE THREAD

**Issue by yjjwxy2** [agiapp/BRPickerView#130]
如题，能不能BRDatePickerModeYMDHMS或者BRDatePickerModeYMD也支持国际化，想要dd-MM-yyyy这样的

**Comment by 91renb** [comment]
参考：https://github.com/91renb/BRPickerView/issues/123

**Comment by yjjwxy2** [comment]
> 参考：#123

我想用自定义格式的BRDatePickerModeYMD

**Comment by 91renb** [comment]
`BRDatePickerModeYMD` 对应的时间格式有很多（亚洲日期：yyyy-MM-dd；美式日期：MM-dd-yyyy；英式日期：dd-MM-yyyy），现在库内部还没实现，替代方案可以使用`UIDatePickerModeDate`

**Comment by 91renb** [comment]
添加了 BRDatePickerModeYMD 支持英式日期（dd-MM-yyyy）
![image](https://user-images.githubusercontent.com/23326671/81792697-fb00d900-953a-11ea-8bf6-54a5902f4e43.png)

**Comment by CainLuo** [comment]
> 添加了 BRDatePickerModeYMD 支持英式日期（dd-MM-yyyy）
> ![image](https://user-images.githubusercontent.com/23326671/81792697-fb00d900-953a-11ea-8bf6-54a5902f4e43.png)

大佬, 有没有办法可以在使用BRDatePickerModeYMD等格式的时候禁止国际化? 使用yyyy-MM-dd中国的格式

**Comment by CainLuo** [comment]
找到一个比较笨的方法了, 直接把style的language写死为zh-Hans-CN就可以实现了

**Comment by 91renb** [comment]
是的，一般是直接设置 language
