### ISSUE TITLE
BRDatePickerStyleSystem系统样式切换BRDatePickerMode,没有效果

### ISSUE THREAD

**Issue by SSPSource** [agiapp/BRPickerView#138]
您好，感谢分享源码，发现用系统样式，切换BRDatePickerMode，没有起到效果。
`- (void)setPickerMode:(BRDatePickerMode)pickerMode {
    _pickerMode = pickerMode;
    // 非空，表示二次设置
    if (_datePicker || _pickerView) {
        [self setupDateFormatter:pickerMode];
        // 刷新选择器数据
        [self reloadData];
        if (self.style == BRDatePickerStyleCustom && self.showUnitType == BRShowUnitTypeOnlyCenter) {
            // 添加时间单位到选择器
            [self addUnitLabel];
        }
    }
}`方法中设置[self setupDateFormatter:pickerMode];虽然_datePickerMode赋值，但是并未对 _datePicker.datePickerMode = _datePickerMode;更新，导致实际没有效果，必须重新初始化UIDatePicker才可以使用，虽然我这边已通过自定义picker解决此问题，依然希望源主可以更新代码，供后面人员使用。谢谢

**Comment by 91renb** [comment]
多谢提醒，已修复。请更新到最新版本
