### ISSUE TITLE
能不能在多列选择器的每一列开头增加一个标题，如下图所示

### ISSUE THREAD

**Issue by LiuWenYu93** [agiapp/BRPickerView#141]
![7C56C7A4-A77E-4601-8F8A-338023BCBD86](https://user-images.githubusercontent.com/20696426/79832646-765be880-83dc-11ea-84fd-8289279192b4.png)

**Comment by 91renb** [comment]
参考README.md，使用如下属性可以添加选择器的头部视图：
```
/** accessory view for above picker view. default is nil */
@property (nullable, nonatomic, strong) UIView *pickerHeaderView;
```
