### ISSUE TITLE
国际化的日期选择样式

### ISSUE THREAD

**Issue by CainLuo** [agiapp/BRPickerView#154]
Version: 2.6.2
iOS Version: 13.5
Xcode: 11.5

当使用BRPickerStyle设置language为zh-Hans, pickerMode设置为BRDatePickerModeYMD, 显示的日期格式yyyy-MM-dd, 但是把language设置为en-us, en-gb, ja-jp显示的日期格式一直都是dd-MM-yyyy, 没有MM-dd-yyyy这种格式吗?

**Comment by 91renb** [comment]
- `BRDatePickerModeYMD`国际化日期目前只兼容英式日期（dd-MM-yyyy），非中文环境下默认都显示英式日期（dd-MM-yyyy）
- `BRDatePickerModeDate`国际化日期兼容英式日期（dd-MM-yyyy）和美式日期（MM-dd-yyyy）

建议你使用`BRDatePickerModeDate`，兼容的国际化日期类型多一点
