### ISSUE TITLE
更新遇到的问题，背景后面可以滑动，下面不能选择了，而且层级上也没有这个控件

### ISSUE THREAD

**Issue by DiaoShiNanShi** [agiapp/BRPickerView#176]
![image](https://user-images.githubusercontent.com/17585895/90787136-fcf6e700-e336-11ea-84d9-cc82e6ea77f8.png)

**Comment by 91renb** [comment]
可能是默认获取的  keyWindow 层级引起的，你可以使用下面这个属性，自己传父视图。
```
/** 组件的父视图：可以传 自己获取的 keyWindow，或页面的 view */
@property (nullable, nonatomic, strong) UIView *keyView;
```
如：
```
... ...
stringPickerView.keyView = self.view; // 也可将组件 stringPickerView 添加到 self.view 上，或 自己获取的 window 上
... ...
```

**Comment by DiaoShiNanShi** [comment]
> 可能是替换获取的keyWindow层级引起的，你可以使用以下这个属性，自己传父视图。
> 
> ```
> /** 组件的父视图：可以传 自己获取的 keyWindow，或页面的 view */
> @property (nullable, nonatomic, strong) UIView *keyView;
> ```
> 
> 如：
> 
> ```
> ... ...
> stringPickerView.keyView = self.view; // 也可将组件 stringPickerView 添加到 self.view 上，或 自己获取的 window 上
> ... ...
> ```

感谢 就是这原因
