### ISSUE TITLE
急急急！！！大佬，为啥选择地址的控件时，香港台湾澳门下边没有二级三级列表呀？？？？

### ISSUE THREAD

**Issue by ke112** [agiapp/BRPickerView#190]
<img width="326" alt="WX20200924-141256@2x" src="https://user-images.githubusercontent.com/45870862/94107468-1af0c380-fe70-11ea-9d31-fd47e8ace5f0.png">

**Comment by 91renb** [comment]
数据来源于民政部：http://www.mca.gov.cn//article/sj/xzqh/2020/2020/20200908007001.html
是没有县和街道、及港澳台数据，省市区数据每个月都会更新调整，实际开发中一般都是从后台获取，根据项目需求 公司内部有个标准就行。使用 `BRAddressPickerView` 或 `BRStringPickerView` 都支持自己传入地区数据源，实现三级联动选择。

**Comment by zhangzhihua2019** [comment]
感谢大佬快速回复，好的，我自己解决一下吧。
