### ISSUE TITLE
列表宽度没有占满屏幕

### ISSUE THREAD

**Issue by wozyao** [agiapp/BRPickerView#191]
![191601016225_ pic](https://user-images.githubusercontent.com/15340066/94235409-14c91880-ff3e-11ea-98d0-4e36c59d84d0.jpg)
Device：Iphone Xr;
OS：iOS14.0.1
demo跑了也是一样的效果。

**Comment by 91renb** [comment]
这个是iOS14上系统新增的默认样式，等下我适配一下

**Comment by wozyao** [comment]
> 这个是iOS14上系统新增的默认样式，等下我适配一下
好的，麻烦给个可以设置的API，谢谢。

**Comment by 91renb** [comment]
已适配iOS14显示样式，同iOS14之前版本显示样式一致，不需要额外再设置API，请更新到最新版本进行使用
