### ISSUE TITLE
时间选择器，两列的情况，如何设置默认行和选中行竖直方向对齐。

### ISSUE THREAD

**Issue by li-qingnan** [agiapp/BRPickerView#196]
![image](https://user-images.githubusercontent.com/10277390/97169105-7215eb00-17c4-11eb-9c63-08e6584fc995.png)
如图显示，如何设置默认行和选中行竖直方向对齐。

**Comment by 91renb** [comment]
这个是系统UIPickerView的默认样式，只有两列时才有这种情况
