### ISSUE TITLE
新版本怎么监听取消点击事件呢？

### ISSUE THREAD

**Issue by 2952883085** [agiapp/BRPickerView#198]
新版本怎么监听取消点击事件呢？

**Comment by 91renb** [comment]
在 `BRBaseView`中有提供如下回调
```
/** 取消选择的回调 */
@property (nullable, nonatomic, copy) BRCancelBlock cancelBlock;
```

**Comment by 2952883085** [comment]
嗯嗯，谢谢了，我已经找到了





------------------ 原始邮件 ------------------
发件人: Renbo <notifications@github.com&gt;
发送时间: 2020年10月27日 18:51
收件人: 91renb/BRPickerView <BRPickerView@noreply.github.com&gt;
抄送: 2952883085 <2952883085@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[91renb/BRPickerView] 新版本怎么监听取消点击事件呢？ (#198)
