### ISSUE TITLE
BRStringPickerView 快速选择后，快速点击确认，返回值没改

### ISSUE THREAD

**Issue by winterwd** [agiapp/BRPickerView#199]
BRStringPickerView 快速选择后，快速点击确认，返回值没改

**Comment by 91renb** [comment]
你可以多测一下，有时候是点击到蒙层了

**Comment by winterwd** [comment]
不是点击到蒙层，跟这个没关系。
的确是会出现的这样的bug，很容易复现的，比如 ： ["男"，"女"]，从 ”男“ 滑动选择 ”女“，然后快速点击确认，返回值还是男。

我猜测这是在切换的动画过程中，点击确认，还是上次的 值，没有发生更改
