### ISSUE TITLE
如果希望在屏幕中央弹窗展示一个选择器需要怎么使用？

### ISSUE THREAD

**Issue by szmichaelyb** [agiapp/BRPickerView#220]
**大佬，您好，有一个业务场景：希望在屏幕中央弹窗展示一个选择器需要怎么使用？**

**Comment by 91renb** [comment]
使用如下方法：

**Comment by szmichaelyb** [comment]
设置 属性 titleBarHeight 后，发现 按钮、标题不居中，太丑了~

![WX20210121-173907@2x.png](https://upload-images.jianshu.io/upload_images/563374-9fa4187597cf7856.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
