### ISSUE TITLE
你好，想问下是否支持这种功能，比如我有三列，我滑动任意一列其他列也跟着滚动，数据都是一一对应的

### ISSUE THREAD

**Issue by Liyongcong** [agiapp/BRPickerView#221]

**Comment by 91renb** [comment]
支持三级联动，使用`BRStringPickerView`
```
/// 字符串选择器类型
typedef NS_ENUM(NSInteger, BRStringPickerMode) {
    /** 单列选择器 */
    BRStringPickerComponentSingle,
    /** 多列选择器 */
    BRStringPickerComponentMulti,
    /** 多级联动选择器 */
    BRStringPickerComponentLinkage
};
```

**Comment by Liyongcong** [comment]
不是三级联动，是一级联动，但是是多个数据拼凑到一块的。我现在是用多个空格处理的，但是感觉这样搞不好，适配比较麻烦，比如下面图片找各种效果






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Renbo"<notifications@github.com&gt;; 
发送时间: 2021年2月3日(星期三) 下午4:34
收件人: "91renb/BRPickerView"<BRPickerView@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [91renb/BRPickerView] 你好，想问下是否支持这种功能，比如我有三列，我滑动任意一列其他列也跟着滚动，数据都是一一对应的 (#221)





 
支持三级联动，使用BRStringPickerView
 /// 字符串选择器类型 typedef NS_ENUM(NSInteger, BRStringPickerMode) {     /** 单列选择器 */     BRStringPickerComponentSingle,     /** 多列选择器 */     BRStringPickerComponentMulti,     /** 多级联动选择器 */     BRStringPickerComponentLinkage };
