### ISSUE TITLE
BRDatePickerView中BRDatePickerModeCountDownTimer手动选取时间失败

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [agiapp/BRPickerView#230]
Demo复现：
Demo中TestViewController.m  305行
改为datePickerView.pickerMode = BRDatePickerModeCountDownTimer
并注释Demo中TestViewController.m  311行
//datePickerView.isAutoSelect = YES;

代码复现：
BRDatePickerView *datePickerView = [[BRDatePickerView alloc]init];
datePickerView.pickerMode = BRDatePickerModeCountDownTimer;
datePickerView.resultBlock = ^(NSDate *selectDate, NSString *selectValue) {
                NSLog(@"selectValue=%@", selectValue);
                NSLog(@"selectDate=%@", selectDate);
                NSLog(@"---------------------------------");
                
};
[datePickerView show];

selectValue 永远为00：00

**Comment by 91renb** [comment]
pickerMode = BRDatePickerModeCountDownTimer时，不要设置`minDate`和`maxDate`
