### ISSUE TITLE
pod repo 索引库中为什么搜不到最新的版本

### ISSUE THREAD

**Issue by jimckylin** [agiapp/BRPickerView#249]
搜索不到最新版本 2.7.5
cocoapods version：1.10.2
pod repo 已更新

**Comment by 91renb** [comment]
由于CocoaPods账号邮箱无法找回，暂时无法上传`2.7.5`版本。可以先暂时使用`pod 'BRPickerView', :git => 'https://github.com/91renb/BRPickerView.git'`  我后面会想办法上传上去。

**Comment by flyweights** [comment]
大佬，保护好账户密码啊！
