### ISSUE TITLE
最新2.1.0版本pods，用bundle加载BRCity.plist为空

### ISSUE THREAD

**Issue by jifusheng** [agiapp/BRPickerView#25]

**Comment by borenfocus** [comment]
// 已更新至2.1.1版本，修改内容如下：
NSBundle *bundle = [NSBundle bundleForClass:[self class]];
NSURL *url = [bundle URLForResource:@"BRPickerView" withExtension:@"bundle"];
NSBundle *plistBundle = [NSBundle bundleWithURL:url];
NSString *filePath = [plistBundle pathForResource:@"BRCity" ofType:@"plist"];

// 非常感谢你提出的问题和解决的方案，现已更新至2.1.1版本，如还有什么问题欢迎指出🙂
