### ISSUE TITLE
文字选项没有居中

### ISSUE THREAD

**Issue by 986138497** [agiapp/BRPickerView#252]
使用第三方BRPickerView的文本选择器，文字选项没有居中，最新版（2.7.5，2021-07-16）未见适配
在 ios15 上

**Comment by jiao808813** [comment]
同样的问题

**Comment by jiao808813** [comment]
iOS15上屏蔽掉setPickerAllSubViewsStyle方法即可
![image](https://user-images.githubusercontent.com/2009467/134654744-216e3439-1e63-4d2d-a702-c834835ba31d.png)

**Comment by 91renb** [comment]
多谢提醒！`v2.7.6`版本已适配

**Comment by 91renb** [comment]
参考 #249，最新版目前暂无法上传到CocoaPods。可以选择手动导入，或`pod 'BRPickerView', :git => 'https://github.com/91renb/BRPickerView.git'` 使用最新版
