### ISSUE TITLE
使用addPickerToView方法，选择器并没有准确获取到父视图的大小。导致滚轮向下偏移。

### ISSUE THREAD

**Issue by firenessZX** [agiapp/BRPickerView#270]
父视图高度是300，采用addPickerToView方法将选择器添加到父视图上，滚轮向下偏移。

**Comment by 91renb** [comment]
要确定一下父视图的frame在添加前后有没有发生变化。使用addPickerToView方法将选择器添加到父视图上，本质是先获取父视图的frame，再将滚轮视图的frame设置成父视图的frame（即安全填充）。如果添加后父视图的frame又发生了变化，会影响滚轮的位置。
