### ISSUE TITLE
内容不显示

### ISSUE THREAD

**Issue by cleven1** [agiapp/BRPickerView#273]
设置了数据源是字符串数组, pickerMode = .componentSingle

颜色设置的是绝对能看得见的 但是内容就是显示不出来, 这是什么原因呢?

使用代码如下:
private lazy var constellationSelected = BRStringPickerView().sc.prepare { view in
        view.title = "请选择星座"
        view.pickerMode = .componentSingle
        view.alertView?.backgroundColor = R.color.color_181F24()
        view.pickerStyle?.pickerColor = .clear
        view.pickerStyle?.pickerTextFont = .uiSize(size: 14)
        view.pickerStyle?.pickerTextColor = R.color.color_ffffff()
        view.pickerStyle?.selectRowTextColor = R.color.color_ffffff()
        view.pickerStyle?.selectRowTextFont = .uiSize(size: 15).medium()
        view.pickerStyle?.titleBarColor = R.color.color_181F24()
        view.pickerStyle?.titleTextColor = R.color.color_ffffff()
        view.pickerStyle?.cancelTextColor = R.color.color_ee4048()
        view.pickerStyle?.doneTextColor = R.color.color_6dd5ed()
        view.dataSourceArr = Util.constellationData()
        view.isAutoSelect = true
        view.selectIndex = 4
        view.resultModelBlock = { [weak self] result in
            self?.constellationButton.setTitle(result?.value, for: .normal)
        }
    }

**Comment by 91renb** [comment]
检查一下数据源，Util.constellationData() 是否有值；另外显示是需要调用show()方法
