### ISSUE TITLE
手动集成报错

### ISSUE THREAD

**Issue by doubleJJJJ** [agiapp/BRPickerView#274]
![1653546445905](https://user-images.githubusercontent.com/12195436/170430492-7cc5f030-9753-41e1-9c5c-5c65f832e2e4.jpg)
如图，手动集成的时候会报错，在BRStringPickerView.m文件的163行，但是用cocoapod集成就不会报错，是什么原因呢？
报错信息：Multiple methods named 'count' found with mismatched result, parameter type or attributes，修改成row = ((index > 0 && index < [(NSArray *)self.mDataSourceArr[i] count]) ? index : 0);就编译通过

**Comment by 91renb** [comment]
我这边编译没有问题，推荐使用最新版本
