### ISSUE TITLE
日期选择器minDate和maxDate的错误

### ISSUE THREAD

**Issue by luckyhong** [agiapp/BRPickerView#300]
/**
 *  3.显示日期选择器
 *
 *  @param mode             日期显示类型
 *  @param title            选择器标题
 *  @param selectValue      默认选中的日期（默认选中当前日期）
 *  @param minDate          最小日期（可使用 NSDate+BRPickerView 分类中对应的方法进行创建）
 *  @param maxDate          最大日期（可使用 NSDate+BRPickerView 分类中对应的方法进行创建）
 *  @param isAutoSelect     是否自动选择，即滚动选择器后就执行结果回调，默认为 NO
 *  @param resultBlock      选择结果的回调
 *
 */
+ (void)showDatePickerWithMode:(BRDatePickerMode)mode
                         title:(nullable NSString *)title
                   selectValue:(nullable NSString *)selectValue
                       minDate:(nullable NSDate *)minDate
                       maxDate:(nullable NSDate *)maxDate
                  isAutoSelect:(BOOL)isAutoSelect
                   resultBlock:(nullable BRDateResultBlock)resultBlock;

提供的这个API建议将minDate和maxDate删除，因为实现里面minDate和maxDate都是传nil，要么实现里面将minDate和maxDate传过去。

**Comment by YidaCoder1201** [comment]
> /**
> 
> * 3.显示日期选择器
> * @param mode             日期显示类型
> * @param title            选择器标题
> * @param selectValue      默认选中的日期（默认选中当前日期）
> * @param minDate          最小日期（可使用 NSDate+BRPickerView 分类中对应的方法进行创建）
> * @param maxDate          最大日期（可使用 NSDate+BRPickerView 分类中对应的方法进行创建）
> * @param isAutoSelect     是否自动选择，即滚动选择器后就执行结果回调，默认为 NO
> * @param resultBlock      选择结果的回调
> 
> */
> 
> * (void)showDatePickerWithMode:(BRDatePickerMode)mode
>   title:(nullable NSString *)title
>   selectValue:(nullable NSString *)selectValue
>   minDate:(nullable NSDate *)minDate
>   maxDate:(nullable NSDate *)maxDate
>   isAutoSelect:(BOOL)isAutoSelect
>   resultBlock:(nullable BRDateResultBlock)resultBlock;
> 
> 提供的这个API建议将minDate和maxDate删除，因为实现里面minDate和maxDate都是传nil，要么实现里面将minDate和maxDate传过去。

为什么不换为第一个或者第二个方法？
