### ISSUE TITLE
仅显示选中行时间单位时时间单位与时间间隔不相同

### ISSUE THREAD

**Issue by g562631649** [agiapp/BRPickerView#303]

**Comment by g562631649** [comment]
求救大佬

**Comment by 91renb** [comment]
怎么个不相同，可以 `setupPickerUnitLabel` 方法里手动调整 unitLabel 的 frame；另外也可以先隐藏单位（`showUnitType=BRShowUnitTypeNone`），可以自定义 label 来设置单位，使用 `addSubViewToPicker` 方法可以把自定义的label添加到组件上。
