### ISSUE TITLE
addPickerToView:样式错乱

### ISSUE THREAD

**Issue by taojeff** [agiapp/BRPickerView#309]
`// 3.创建选择器容器视图
    UIView *containerView = [[UIView alloc]initWithFrame:CGRectMake(30, 170, self.view.frame.size.width - 60, 200)];
    containerView.backgroundColor = UIColor.redColor;
    containerView.autoresizingMask = UIViewAutoresizingFlexibleWidth;
    [self.view addSubview:containerView];
    

    // 4.创建日期选择器
    BRDatePickerView *datePickerView = [[BRDatePickerView alloc]init];
    datePickerView.pickerMode = BRDatePickerModeDateAndTime;
    datePickerView.maxDate = [NSDate date];
    datePickerView.isAutoSelect = YES;
    datePickerView.showUnitType = BRShowUnitTypeOnlyCenter;
    datePickerView.resultBlock = ^(NSDate *selectDate, NSString *selectValue) {
        if (self.timeType == BRTimeTypeBeginTime) {
            self.beginSelectDate = selectDate;
            self.beginTimeTF.text = selectValue;
        } else if (self.timeType == BRTimeTypeEndTime) {
            self.endSelectDate = selectDate;
            self.endTimeTF.text = selectValue;
        }
    };
    
    // 自定义选择器主题样式
    BRPickerStyle *customStyle = [[BRPickerStyle alloc]init];
    customStyle.pickerColor = containerView.backgroundColor;
    datePickerView.pickerStyle = customStyle;、
    
    // 添加选择器到容器视图
    [datePickerView addPickerToView:containerView];`
<img width="359" alt="image" src="https://github.com/agiapp/BRPickerView/assets/19642626/0c250469-b535-4b46-8d2f-39eb5a1fb140">
我将pickview放在view上后发现样式布局错了

**Comment by taojeff** [comment]
> 已修复，请更新到最新版本进行使用

多谢，博主，如果有时间的话是否可以更新一个新的样式“年月日周、时、分、秒”这样四列滚轮样式

**Comment by agiapp** [comment]
针对需要显示星期的场景，可以配合设置 `datePickerView.showWeek = YES;` 来达到类似的效果
# 代码
```
BRDatePickerView *datePickerView = [[BRDatePickerView alloc]init];
datePickerView.pickerMode = BRDatePickerModeYMDHMS;
datePickerView.showWeek = YES;
datePickerView.resultBlock = ^(NSDate *selectDate, NSString *selectValue) {
    
};
[datePickerView show];
```

# 效果
![image](https://github.com/agiapp/BRPickerView/assets/23326671/86655783-62e5-439a-97d3-c247736b6098)

**Comment by taojeff** [comment]
我知道这样可以，可是我这边想要做的是第一个滚轮是年月日周，第二个滚轮是时，第三个是分，第四个是秒。




990073834
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "agiapp/BRPickerView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月28日(星期二) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [agiapp/BRPickerView] addPickerToView:样式错乱 (Issue #309)





 
针对需要显示星期的场景，可以配合设置 datePickerView.showWeek = YES; 来达到类似的效果
 
代码
 BRDatePickerView *datePickerView = [[BRDatePickerView alloc]init]; datePickerView.pickerMode = BRDatePickerModeYMDHMS; datePickerView.showWeek = YES; datePickerView.resultBlock = ^(NSDate *selectDate, NSString *selectValue) {      }; [datePickerView show];  
效果
 
image.png (view on web)
