### ISSUE TITLE
希望reloadData时有加个动画

### ISSUE THREAD

**Issue by wtuyp** [agiapp/BRPickerView#311]
希望reloadData时有个动画，可以加个方法。
- (void)reloadDataWithAnimated; 或 - (void)reloadDataWithAnimated:(BOOL)animated;
谢谢！

**Comment by agiapp** [comment]
可以描述一下具体需求场景，reloadData方法里面调用[self.pickerView reloadAllComponents];是不带动画参数的

**Comment by wtuyp** [comment]
@agiapp 
比如 两列字符串选择器，第一列1到10数字，第二列1到10数字。第二列选中的数字不能大于过第一列。
操作：当第一列选3时，第二列如果选了6，第二列需要动画回滚到3。

现在在 changeModelArrayBlock 中比较大小后，需要回滚时调用了 [self.pickerView reloadData];
而 reloadData 方法中调用 [self.pickerView selectRow:[index integerValue] inComponent:i animated:NO];
这里的 animated 是 NO，所以没有动画效果。如果有个选择可以设置 animated 为 YES 来实现动画是否可行？

**Comment by agiapp** [comment]
新增了如下属性
```
/** 滚动至选择行动画，默认为 NO */
@property (nonatomic, readonly, assign) BOOL selectRowAnimated;
```
说明：最新版新增了`BRTextPickerView`组件，具体使用请参见 README.md

**Comment by wtuyp** [comment]
@agiapp 你好，selectRowAnimated 属性是 readonly，没有办法设置属性。

**Comment by agiapp** [comment]
已更新
