### ISSUE TITLE
在iOS 18 上崩溃

### ISSUE THREAD

**Issue by Asingers** [agiapp/BRPickerView#314]
`
*** Assertion failure in -[BRStringPickerView _addSubview:positioned:relativeTo:], UIView.m:18428
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Set `maskView` (<UIView: 0x15eee3640; frame = (0 0; 414 896); autoresize = W+RM+H+BM; gestureRecognizers = <NSArray: 0x3028a1170>; backgroundColor = <UIDynamicProviderColor: 0x302a76ec0; provider = <__NSMallocBlock__: 0x3024cf6f0>>; layer = <CALayer: 0x302a11580>>) to `nil` before adding it as a subview of <BRStringPickerView: 0x15f16fc00; frame = (0 0; 414 896); autoresize = W+RM+H+BM; layer = <CALayer: 0x302a15b80>>'
`

**Comment by ClockCake** [comment]
+ 1 BRBaseView
Thread 1: "Set `maskView` (<UIView: 0x108c11730; frame = (0 0; 393 852); autoresize = W+RM+H+BM; gestureRecognizers = <NSArray: 0x600000020b10>; backgroundColor = <UIDynamicProviderColor: 0x6000002c9ee0; provider = <__NSMallocBlock__: 0x600000cf0f60>>; layer = <CALayer: 0x6000002c9c60>>) to `nil` before adding it as a subview of <BRStringPickerView: 0x108c08190; frame = (0 0; 393 852); autoresize = W+RM+H+BM; layer = <CALayer: 0x6000002396e0>>"

**Comment by agiapp** [comment]
已修复，请更新到最新版本进行使用。奔溃原因是maskView自定义视图命名与系统组件命名冲突。
