### ISSUE TITLE
获取选中下标

### ISSUE THREAD

**Issue by Liyongcong** [agiapp/BRPickerView#47]
怎么获取到选中的下标呢

**Comment by yanrongxiang** [comment]
我也发现获取不了索引，很多需求下自己的数据是有很多属性的，获取不到下标就用不了。自己小改了下
![default](https://user-images.githubusercontent.com/3411744/44707370-eb2b3200-aad6-11e8-8986-bc5d3dc22d0a.png)
![default](https://user-images.githubusercontent.com/3411744/44707386-f5e5c700-aad6-11e8-9949-4ce808c32b9a.png)

**Comment by Liyongcong** [comment]
我加过了
