### ISSUE TITLE
我拿到单列的值，怎么拿到当前选中对应的索引呢。

### ISSUE THREAD

**Issue by zhaomengshan** [agiapp/BRPickerView#55]

**Comment by 91renb** [comment]
你可以先暂时这样获取，我后期会在resultBlock的回调中加上索引。

// 自定义单列字符串
NSArray *dataSource = @[@"大专以下", @"大专", @"本科", @"硕士", @"博士", @"博士后"];
NSString *selectedValue = @"本科";
[BRStringPickerView showStringPickerWithTitle:@"学历" dataSource:dataSource defaultSelValue:selectedValue isAutoSelect:YES themeColor:nil resultBlock:^(id selectValue) {
    NSLog(@"选择的值：%@", selectValue);
    NSLog(@"选择的值对应的索引：%@", [dataSource indexOfObject:selectValue]);
} cancelBlock:nil];

**Comment by zhaomengshan** [comment]
谢谢啊

**Comment by DogTwoChen** [comment]
那如果数组里面有数据相同呢?
