### ISSUE TITLE
国际化，字体，颜色，等问题

### ISSUE THREAD

**Issue by firenessZX** [agiapp/BRPickerView#59]
老铁，你应该把所有能显示的东西都暴露成属性，可以让使用者自由的设置，比如按钮字体，大小，颜色，标题大小，颜色，以及国际化等等。

**Comment by Xianyus** [comment]
+1

**Comment by A-Jun** [comment]
+1 我还要自己改 - -！

**Comment by luo-h** [comment]
+1

**Comment by luo-h** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
