### ISSUE TITLE
关于dataSource数组中类型不一的问题。

### ISSUE THREAD

**Issue by shenhaojicool** [agiapp/BRPickerView#60]
比如array = @[str1,str2,str3];
三个string类型的，应该是可以的。
但是如果一个是__NSCFConstantString,
一个是__NSCFString
另外一个是NSTaggedPointerString。这样都崩溃，需要自己处理成统一的。期望可以优化一下

**Comment by zjxsilence** [comment]
同上，希望可以优化一下。。。

**Comment by diidiid** [comment]
+1，同遇到这个问题

**Comment by luckyhong** [comment]
+1
