### ISSUE TITLE
您好，这个库不支持自定义二级动态选择吗？

### ISSUE THREAD

**Issue by yimao009** [agiapp/BRPickerView#66]
自定义字符串二级动态选择好像不支持，只能写死数据， 

右侧的列表根据左侧的选择不同展示不一样的数据； 我觉的咱们这个库也可以支持这个大众需求；

**Comment by Jayxiang** [comment]
同需求。

**Comment by yimao009** [comment]
> 同需求。

我又借助这个库自定义了二级动态选择；虽然在我项目里能用，但是有点不解耦； 不能独立出一个组件

**Comment by che11o2u** [comment]
用城市列表的picker传自己数据就好了，3列一下可以用，另外需要自己改title

**Comment by 91renb** [comment]
该功能已实现，字符串选择器新增支持多级联动选择，请参看Demo进行使用
