### ISSUE TITLE
日期选择器可以只精确到小时吗？

### ISSUE THREAD

**Issue by lumianie** [agiapp/BRPickerView#92]
目前提供的要么到天，再就是到分钟，没有精确到小时类型的嘛

**Comment by 91renb** [comment]
目前只列了常用的几种类型，你是需要 yyyy-MM-dd HH （年月日时）这种类型吗？

**Comment by lumianie** [comment]
> 目前只列了常用的几种类型，你是需要 yyyy-MM-dd HH （年月日时）这种类型吗？

嗯嗯对啊，这个需求其实蛮常见的，不支持的话就只能改源码了哈哈

**Comment by 91renb** [comment]
我等会儿给你加上去，日期新增 yyyy-MM-dd HH 这种类型

**Comment by lumianie** [comment]
> 我等会儿给你加上去，日期新增 yyyy-MM-dd HH 这种类型

谢谢

**Comment by 91renb** [comment]
已更新
